# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: mongar 0.0.12 ruby lib

Gem::Specification.new do |s|
  s.name = "mongar".freeze
  s.version = "0.0.12"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Philippe Green".freeze]
  s.date = "2018-03-19"
  s.description = "Replicates data from ActiveRecord (or other Ruby data mapping class) to MongoDB".freeze
  s.email = "phil@greenviewdata.com".freeze
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/mongar.rb",
    "lib/mongar/column.rb",
    "lib/mongar/mongo.rb",
    "lib/mongar/mongo/collection.rb",
    "lib/mongar/replica.rb",
    "mongar.gemspec",
    "spec/fixtures/configure.rb",
    "spec/fixtures/full_configure.rb",
    "spec/fixtures/sources.rb",
    "spec/integration_spec.rb",
    "spec/mongar/column_spec.rb",
    "spec/mongar/mongo/collection_spec.rb",
    "spec/mongar/mongo_spec.rb",
    "spec/mongar/replica_spec.rb",
    "spec/mongar_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/gdi/mongar".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "2.7.3".freeze
  s.summary = "Replicates data from ActiveRecord (or other Ruby data mapping class) to MongoDB".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<linguistics>.freeze, ["~> 2.1"])
      s.add_runtime_dependency(%q<mongo>.freeze, ["~> 2.4"])
      s.add_development_dependency(%q<rake>.freeze, ["< 11.0"])
      s.add_development_dependency(%q<rspec>.freeze, ["~> 2.14"])
      s.add_development_dependency(%q<yard>.freeze, ["~> 0.9"])
      s.add_development_dependency(%q<bundler>.freeze, ["~> 1.14"])
      s.add_development_dependency(%q<jeweler>.freeze, ["~> 2.3"])
    else
      s.add_dependency(%q<linguistics>.freeze, ["~> 2.1"])
      s.add_dependency(%q<mongo>.freeze, ["~> 2.4"])
      s.add_dependency(%q<rake>.freeze, ["< 11.0"])
      s.add_dependency(%q<rspec>.freeze, ["~> 2.14"])
      s.add_dependency(%q<yard>.freeze, ["~> 0.9"])
      s.add_dependency(%q<bundler>.freeze, ["~> 1.14"])
      s.add_dependency(%q<jeweler>.freeze, ["~> 2.3"])
    end
  else
    s.add_dependency(%q<linguistics>.freeze, ["~> 2.1"])
    s.add_dependency(%q<mongo>.freeze, ["~> 2.4"])
    s.add_dependency(%q<rake>.freeze, ["< 11.0"])
    s.add_dependency(%q<rspec>.freeze, ["~> 2.14"])
    s.add_dependency(%q<yard>.freeze, ["~> 0.9"])
    s.add_dependency(%q<bundler>.freeze, ["~> 1.14"])
    s.add_dependency(%q<jeweler>.freeze, ["~> 2.3"])
  end
end

